language: java
jdk:
- oraclejdk8
before_install:
- sudo chmod a+x ./travis/*.sh
- "./travis/before_install.sh"
install: "./travis/install.sh"
# source keyword is needed for DO_DEPLOY variable to propagate to condition below 
script: "source ./travis/script.sh"
notifications:
  email:
    recipients:
    - jindra.petrik@gmail.com
    on_success: change
    on_failure: always
before_deploy: "./travis/before_deploy.sh"    
deploy:
  provider: script
  script: "source ./travis/deploy.sh"
  skip_cleanup: true  
  on:
    repo: jindrapetrik/updatetest
    all_branches: true
    condition: $DO_DEPLOY = 1
